# Generated by Django 5.1.15 on 2026-04-05 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('manual', 'Manual (admin)')], max_length=20, verbose_name='Gateway')),
                ('gateway_payment_id', models.CharField(blank=True, max_length=200, verbose_name='ID externo (gateway)')),
                ('gateway_preference_id', models.CharField(blank=True, max_length=200, verbose_name='ID da preferência (MP)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('in_process', 'Em processo'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Resposta bruta do gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
