# Generated by Django 5.1.15 on 2026-04-05 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone (classe CSS)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('lesson_type', models.CharField(choices=[('video', 'Vídeo'), ('pdf', 'PDF'), ('text', 'Texto')], max_length=10, verbose_name='Tipo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Aula gratuita (prévia)')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duração (minutos)')),
                ('video_url', models.URLField(blank=True, verbose_name='URL do vídeo (YouTube/Vimeo)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Arquivo de vídeo')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lessons/pdfs/', verbose_name='Arquivo PDF')),
                ('text_content', models.TextField(blank=True, verbose_name='Conteúdo em texto/HTML')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('last_position_seconds', models.PositiveIntegerField(default=0, verbose_name='Posição no vídeo (seg)')),
            ],
            options={
                'verbose_name': 'Progresso de Aula',
                'verbose_name_plural': 'Progresso de Aulas',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('level', models.CharField(choices=[('eja_fund', 'EJA Fundamental II'), ('eja_medio', 'EJA Ensino Médio'), ('tecnico', 'Técnico')], max_length=20, verbose_name='Nível')),
                ('modality', models.CharField(choices=[('presencial', 'Presencial'), ('ead', 'EAD'), ('hibrido', 'Híbrido (EAD + Presencial)')], default='ead', max_length=20, verbose_name='Modalidade')),
                ('description', models.TextField(verbose_name='Descrição completa')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Descrição curta')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Imagem de capa')),
                ('promo_video_url', models.URLField(blank=True, verbose_name='URL do vídeo promocional')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (à vista)')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço antes do desconto', max_digits=10, null=True, verbose_name='Preço original (riscado)')),
                ('workload_hours', models.PositiveIntegerField(verbose_name='Carga horária (horas)')),
                ('duration_months', models.PositiveIntegerField(default=6, verbose_name='Duração (meses)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na home')),
                ('has_internship', models.BooleanField(default=False, verbose_name='Possui estágio')),
                ('internship_hours', models.PositiveIntegerField(default=0, verbose_name='Horas de estágio')),
                ('certificate_template', models.FileField(blank=True, null=True, upload_to='courses/certificates/', verbose_name='Template do certificado')),
                ('meta_title', models.CharField(blank=True, max_length=250, verbose_name='Meta title (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='Meta description (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Matriculado em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificado gerado')),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Certificado emitido em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
